### PR TITLE
dq_invalid_months_times_homeless

### PR DESCRIPTION
**Pull request by yogat3ch**
See commit for details

### CODE REVIEW

**Comment by gwenbeebe** [comment]
These changes all look good! I'm realizing now that I'm reviewing it though--we should probably have pulled the `"Homelessness Start Date Later Than Entry"` check out into its own function. Right now it can only trigger for clients that are recorded as having a single episode of homelessness (line 927), but this would be an error wherever it happens.

**Comment by yogat3ch** [comment]
> we should probably have pulled the `"Homelessness Start Date Later Than Entry"` check out into its own function. 

Thanks for catching this @gwenbeebe! Would this new function (say `dq_start_later_than_entry`) retain all of the logic except for [line 927](https://github.com/COHHIO/Rm_data/pull/3/files#diff-8f53e04da52217db0e8d8ad8d182c4a4d11abe717e40e5e6c2a4b8cb2c4392f7R927)? Would you feel comfortable creating this dq check function? I'm a little confused what it needs to include.

**Comment by gwenbeebe** [comment]
Hey Stephen, I pulled the conditions out into a second test and then looked at how much they still had in common, and recombined. I think what makes the most sense here is just moving the condition requiring a single episode of homelessness into the two warnings that actually require it, because that way line 964 filters them out anyway if they don't meet all the criteria for that particular flag!

**Comment by yogat3ch** [comment]
Thank you @gwenbeebe for fixing this logic! Merging now!

**Pull request merged**
